### ISSUE TITLE
Consider changing to a PluginHub compatible license such as MIT or BSD

### ISSUE THREAD

**Issue by TheAtomicOption** [sethrem/bronzeman#6]
As seen in this pull request: https://github.com/runelite/plugin-hub/pull/151  Updated versions of this plugin are not able to be listed on Runelite's new PluginHub because the GPL 3.0 is too restrictive. This is highly unfortunate since that fork of this plugin has a better feature set than existing plugin hub bronzeman implementations by other authors, and is the only one that gives you attribution.

**Comment by CodePanter** [comment]
I have started anew in a new repository where I rewrote most code and kept all my own code. My code is still based on sethrem's original design, which is why he is still credited in the readme file. See my repository here: https://github.com/CodePanter/another-bronzeman-mode

**Comment by sethrem** [comment]
I can def do this, and yea man sadly no one has crdited me besides @CodePanter . Thank you going to update this plugin a bit.

**Comment by bronzie-boo** [comment]
hey can u guys help me? ive built runelite and it runs, but i cant find bronzemanmode in the plugins on intelliJ IDEA. all the plugins are there except bronzeman, so i cant compile it to runelite because it isnt there. im stuck at this part

**Comment by TheAtomicOption** [comment]
At this point the better option is to use the official runelite release and install through the plugin hub as I believe the fork of this repo that I mention above is one of the options. I'm not aware of any remaining advantage to using a version you have to compile yourself.

Closing this issue as the license has been changed to MIT as requested and further discussion is off topic.
